### ISSUE TITLE
Loot drops but won't teleport

### ISSUE THREAD

**Issue by MuffinCrow** [rhydiaan/NicerTeleporters#4]
A lot of the time the teleporter will drop your loot but won't teleport you. Not sure what is causing this.

**Comment by rhydiaan** [comment]
I haven't noticed this, I'll look into it this week and hopefully get this sorted. Could you give a tiny bit more detail on when it happens please?

**Comment by rhydiaan** [comment]
Also is this for both inverse and normal teleporter or only one specifically?

**Comment by MuffinCrow** [comment]
Sorry for the late reply. It generally happens when we are attempting to teleport a player that is holding both loot and items. I know for a fact we sometimes end up canceling the teleport by picking up items so it may be in regards to that. We have not experienced issues with the inverse teleporter but that may be because we only use it at the beginning of the round before picking up loot.

**Comment by rhydiaan** [comment]
I'll look into it this week, thanks for letting me know. I was unable to replicate any of this last week but I didn't try picking things up mid teleport. Will keep you posted.

**Comment by ArsenicBismuth** [comment]
I got this issue too (for normal teleporter) and most of the time during crucial moment. The visual effect would run, but once it's done, the body (alive) is not teleporting. Which causes my friend being killed multiple times.

I don't know the specifics about the loot, whether it's dropped or not.

**Comment by rhydiaan** [comment]
I am trying to figure this out still, I can't really understand why this would be happening because I haven't altered the teleporter behaviour itself, only the drop items. From what I can tell based on both your experiences it would be the way I'm patching it so I'll try figuring a way around that. I appreciate you guys being patient.

**Comment by rhydiaan** [comment]
I am unable to replicate this behaviour so my other thought would be conflicting mods. Could you guys provide a list of all the mods you're using when this happens please?
